### ISSUE TITLE
Reorder decision tree questions: don't start in the middle

### ISSUE THREAD

**Issue by sjvrijn** [SS-NES/docassemble-SMPDecisionTree#28]
In the current decision tree questions we start 'in the middle' regarding whether and what kind of additional users the software will have.
Feedback from the walk-in sessions indicates that this leads to confusion about the used definitions of (external) users.

Instead, we're probably better off first asking if *any* users other than the developer themselves are expected, and only further specifying from there, to better guide the user through our different kinds of user definitions.

**Comment by OleMussmann** [comment]
New, linear order:
- Reusable
- Multi-user
- Community

**Comment by OleMussmann** [comment]
Fixed in https://github.com/SS-NES/docassemble-SMPDecisionTree/commit/3007cbc4a4b3de46584a6885d2947f550369641a
